// Generated by CoffeeScript 1.6.2
(function() {
  var __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define(["bindable", "../utils/async", "cstep", "asyngleton", "../utils/throttleCallback"], function(bindable, async, cstep, asyngleton, throttleCallback) {
    var callbackThrottle;

    callbackThrottle = throttleCallback(20);
    return (function(_super) {
      __extends(_Class, _super);

      function _Class() {
        this._displayLateItems = __bind(this._displayLateItems, this);
        this._displayLateItem = __bind(this._displayLateItem, this);        _Class.__super__.constructor.apply(this, arguments);
        this.enforceId(false);
      }

      /*
      */


      _Class.prototype.limit = 1;

      /*
       loads the template, and anything else that might be needed
      */


      _Class.prototype.load = asyngleton(function(callback) {
        return this._callViewMethod("load", "loaded", callback);
      });

      /*
       renders the view
      */


      _Class.prototype.render = asyngleton(function(callback) {
        var _this = this;

        return this.load(function() {
          return _this._callViewMethod("render", "rendered", callback);
        });
      });

      /*
       called when we want to display the view
      */


      _Class.prototype.display = asyngleton(function(callback) {
        var _this = this;

        return this.render(function() {
          _this.on("insert", _this._displayLateItem);
          _this.on("reset", _this._displayLateItems);
          return _this._callViewMethod("display", "displayed", callback);
        });
      });

      /*
       removes & unloads the view
      */


      _Class.prototype.remove = asyngleton(function(callback) {
        var _this = this;

        return this.display(function() {
          return _this._callViewMethod("remove", "removed", callback);
        });
      });

      /*
      */


      _Class.prototype.emit = function() {
        var _ref;

        _Class.__super__.emit.apply(this, arguments);
        return (_ref = this.view) != null ? _ref.emit.apply(_ref, arguments) : void 0;
      };

      /*
      */


      _Class.prototype._callViewMethod = function(method, event, callback) {
        var done, run,
          _this = this;

        if (callback == null) {
          callback = (function() {});
        }
        this.emit(method);
        run = function(item, next) {
          var fn;

          fn = item[method];
          if (!fn) {
            return next();
          }
          return callbackThrottle.call(item, fn, next);
        };
        done = function(err, result) {
          _this.emit(event);
          if (err) {
            return callback(err);
          }
          return callback();
        };
        if (!~this.limit) {
          return async.forEach(this.source(), run, done);
        } else {
          return async.eachLimit(this.source(), this.limit, run, done);
        }
      };

      /*
      */


      _Class.prototype._displayLateItem = function(item) {
        return item.display();
      };

      /*
      */


      _Class.prototype._displayLateItems = function(items) {
        return this._callViewMethod("display", "displayed");
      };

      return _Class;

    })(bindable.Collection);
  });

}).call(this);
