// Generated by CoffeeScript 1.6.2
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define(["./base", "./decor/factory"], function(BaseView, DecorFactory) {
    var DecoratedView, _ref;

    return DecoratedView = (function(_super) {
      __extends(DecoratedView, _super);

      function DecoratedView() {
        _ref = DecoratedView.__super__.constructor.apply(this, arguments);
        return _ref;
      }

      return DecoratedView;

    })(BaseView);
  });

}).call(this);
