// Generated by CoffeeScript 1.6.2
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define(["require", "./base", "bindable", "underscore", "async"], function(require, BaseView, bindable, _, async) {
    var ContainerView, _ref;

    return ContainerView = (function(_super) {
      __extends(ContainerView, _super);

      function ContainerView() {
        _ref = ContainerView.__super__.constructor.apply(this, arguments);
        return _ref;
      }

      /*
      */


      ContainerView.prototype.childrenElement = ".children";

      /*
      */


      ContainerView.prototype.childElement = "div";

      return ContainerView;

    })(BaseView);
  });

}).call(this);
