// Generated by CoffeeScript 1.6.2
(function() {
  define([], function() {
    var Popup;

    Popup = (function() {
      /*
      */
      function Popup() {}

      return Popup;

    })();
    Popup.show = function(clazz) {
      var view;

      view = new clazz();
      view.attach($("body").append("<div></div>").children().last());
      return view;
    };
    return Popup;
  });

}).call(this);
