// Generated by CoffeeScript 1.6.3
var StatesView, _ref,
  __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

StatesView = (function(_super) {
  __extends(StatesView, _super);

  function StatesView() {
    this._setIndex = __bind(this._setIndex, this);
    _ref = StatesView.__super__.constructor.apply(this, arguments);
    return _ref;
  }

  /*
  */


  StatesView.prototype._init = function() {
    StatesView.__super__._init.call(this);
    return this.bind("index", this._setIndex);
  };

  /*
  */


  StatesView.prototype._setIndex = function(index) {};

  return StatesView;

})(require("./base"));

module.exports = StatesView;
