


define(["require", "modules/mojo/interm/views/index", "modules/mojo/interm/mediator/index", "bindable"], function(require) {

    var __dirname = "modules/mojo/interm",
    __filename    = "modules/mojo/interm/index.js",
    module        = { exports: {} },
    exports       = module.exports,
    define        = undefined,
    window        = exports,
    global        = window;

    

    // Generated by CoffeeScript 1.6.2
(function() {
  var View, bindable, mediator;

  View = require("modules/mojo/interm/views/index");

  mediator = require("modules/mojo/interm/mediator/index");

  bindable = require("bindable");

  module.exports = {
    View: View,
    mediator: mediator,
    bindable: bindable
  };

}).call(this);


    return module.exports;
});