// Generated by CoffeeScript 1.6.2
(function() {
  define(["./views/helloWorld"], function(HelloWorldView) {
    return new HelloWorldView({
      name: "craig"
    }).attach($("body"));
  });

}).call(this);
