// Generated by CoffeeScript 1.6.2
(function() {
  var Adapter;

  Adapter = (function() {
    function Adapter() {}

    /*
     returns a bindable object
    */


    Adapter.prototype.getModel = function(model) {};

    /*
     returns a bindable collection
    */


    Adapter.prototype.getCollection = function(collection) {};

    /*
     returns a mojo view
    */


    Adapter.prototype.getViewClass = function(viewClass) {};

    return Adapter;

  })();

  module.exports = Adapter;

}).call(this);
