// Generated by CoffeeScript 1.6.2
(function() {
  var State, bindable, _,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  bindable = require("bindable");

  _ = require("underscore");

  State = (function(_super) {
    __extends(State, _super);

    /*
    */


    function State(states, options, index) {
      var ops;

      this.states = states;
      this.select = __bind(this.select, this);
      ops = {};
      if (!options.viewClass && !options["class"]) {
        ops.viewClass = options;
      } else {
        ops = options;
      }
      ops.index = index;
      ops.selected = false;
      ops._id = options.name || Math.random();
      State.__super__.constructor.call(this, this);
      this.setProperties(ops);
    }

    /*
    */


    State.prototype.select = function() {
      return this.states.select(this);
    };

    /*
    */


    State.prototype.remove = function() {
      this._view.set("visible", false);
      this._view.dispose();
      return this._view = void 0;
    };

    /*
    */


    State.prototype.render = function() {
      this._view.set("visible", true);
      return this._view.render();
    };

    /*
    */


    State.prototype.hasView = function() {
      return !!this._view;
    };

    /*
    */


    State.prototype.getView = function() {
      var clazz, _ref;

      if (this._view) {
        return this._view;
      }
      clazz = (_ref = this.get("class")) != null ? _ref : this.get("viewClass");
      return this._view = new clazz();
    };

    return State;

  })(bindable.Object);

  module.exports = State;

}).call(this);
