


define(["require", "modules/bindable/lib/collection/setters/base"], function(require) {

    var __dirname = "modules/bindable/lib/collection/setters",
    __filename    = "modules/bindable/lib/collection/setters/fn.js",
    module        = { exports: {} },
    exports       = module.exports,
    define        = undefined,
    window        = exports,
    global        = window;

    

    // Generated by CoffeeScript 1.6.2
(function() {
  var _ref,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  module.exports = (function(_super) {
    __extends(_Class, _super);

    function _Class() {
      _ref = _Class.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    /*
    */


    _Class.prototype.init = function() {
      var i, item, _i, _len, _ref1, _results;

      _Class.__super__.init.call(this);
      _ref1 = this.binding._from.source();
      _results = [];
      for (i = _i = 0, _len = _ref1.length; _i < _len; i = ++_i) {
        item = _ref1[i];
        _results.push(this.change("insert", item));
      }
      return _results;
    };

    /*
    */


    _Class.prototype._change = function(method, item, oldItems) {
      return this.target(method, item, oldItems);
    };

    return _Class;

  })(require("modules/bindable/lib/collection/setters/base"));

}).call(this);


    return module.exports;
});