


define(["require", "modules/bindable/lib/core/utils"], function(require) {

    var __dirname = "modules/bindable/lib/object/setters",
    __filename    = "modules/bindable/lib/object/setters/base.js",
    module        = { exports: {} },
    exports       = module.exports,
    define        = undefined,
    window        = exports,
    global        = window;

    

    // Generated by CoffeeScript 1.6.2
(function() {
  var utils;

  utils = require("modules/bindable/lib/core/utils");

  module.exports = (function() {
    /*
    */
    function _Class(binding) {
      this.binding = binding;
      this._transformer = this.binding.transform();
      this.now();
    }

    /*
    */


    _Class.prototype.now = function() {
      return this.change(this.binding._from.get(this.binding._property), !this.binding.watch());
    };

    /*
    */


    _Class.prototype.change = function(value, call) {
      var transformedValue;

      if (this.currentValue === value) {
        return;
      }
      transformedValue = this.__transform("to", value);
      if (this.currentValue === transformedValue) {
        return;
      }
      this.currentValue = transformedValue;
      if (call === false) {
        return;
      }
      return this._change(transformedValue);
    };

    /*
    */


    _Class.prototype.bothWays = function() {};

    /*
    */


    _Class.prototype._change = function(value) {};

    /*
    */


    _Class.prototype.__transform = function(method, value) {
      return utils.tryTransform(this._transformer, method, value);
    };

    return _Class;

  })();

}).call(this);


    return module.exports;
});