// Generated by CoffeeScript 1.6.2
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define(["../base/index"], function(BaseAdapter) {
    var BackboneAdapter, _ref;

    return BackboneAdapter = (function(_super) {
      __extends(BackboneAdapter, _super);

      function BackboneAdapter() {
        _ref = BackboneAdapter.__super__.constructor.apply(this, arguments);
        return _ref;
      }

      /*
      */


      BackboneAdapter.prototype.getModel = function(value) {
        if (!value.idAttribute) {
          return false;
        }
        return console.log("MODEL");
      };

      /*
      */


      BackboneAdapter.prototype.getCollection = function(value) {};

      /*
      */


      BackboneAdapter.prototype.getView = function(value) {};

      return BackboneAdapter;

    })(BaseAdapter);
  });

}).call(this);
