// Generated by CoffeeScript 1.6.2
(function() {
  define(["../../base"], function(BaseView) {
    return BaseView = (function() {
      /*
      */
      function BaseView() {}

      return BaseView;

    })();
  });

}).call(this);
