// Generated by CoffeeScript 1.4.0

/*
templates.use(i 8n)
*/


(function() {

  define(["./loader!"], function(translator) {
    return function(text) {
      return translator.t(text);
    };
  });

}).call(this);
