// Generated by CoffeeScript 1.4.0
(function() {

  define(function() {
    var BaseEngine;
    return BaseEngine = (function() {
      /*
      */

      function BaseEngine(factory) {
        this.factory = factory;
        this.init();
      }

      /*
      */


      BaseEngine.prototype.init = function() {};

      /*
           renders a template - must always be asynchronous
      */


      BaseEngine.prototype.compile = function(source) {
        throw new Error("must be overridden");
      };

      return BaseEngine;

    })();
  });

}).call(this);
