// Generated by CoffeeScript 1.6.2
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define(["bindable", "pilot-block"], function(bindable, pilot) {
    var Decor;

    return Decor = (function(_super) {
      __extends(Decor, _super);

      /*
      */


      function Decor(decorator, options) {
        this.decorator = decorator;
        this.options = options;
        Decor.__super__.constructor.call(this);
        this._id = this.name = options._name;
        this.view = decorator.view;
        this.sectionName = options.section;
        this.itemName = options.name || "item";
        this.section = pilot.createSection();
      }

      /*
      */


      Decor.prototype.load = function(callback) {
        var _this = this;

        return this._load(function() {
          if (_this.sectionName === "html" && !_this.view.template) {
            _this.view.section.append(_this.section);
          } else {
            _this.view.set(_this.sectionName, _this.section);
          }
          return callback();
        });
      };

      /*
      */


      Decor.prototype._load = function(next) {};

      return Decor;

    })(bindable.Object);
  });

}).call(this);
