// Generated by CoffeeScript 1.6.2
(function() {
  define([], function() {
    var Adapter;

    return Adapter = (function() {
      function Adapter() {}

      /*
       returns a bindable object
      */


      Adapter.prototype.getItem = function(item) {};

      /*
       returns a bindable collection
      */


      Adapter.prototype.getCollection = function(collection) {};

      /*
       returns a mojo view
      */


      Adapter.prototype.getView = function(view) {};

      return Adapter;

    })();
  });

}).call(this);
