// Generated by CoffeeScript 1.6.2
(function() {
  define(["./backbone/index"], function(BackboneAdapter) {
    var Adapter;

    return Adapter = (function() {
      /*
      */
      function Adapter() {
        this._adapters = [new BackboneAdapter()];
      }

      /*
       returns a bindable object
      */


      Adapter.prototype.getItem = function(value) {
        return this._get("getItem", value);
      };

      /*
       returns a bindable collection
      */


      Adapter.prototype.getCollection = function(value) {
        return this._get("getCollection", value);
      };

      /*
       returns a mojo view
      */


      Adapter.prototype.getView = function(value) {
        return this._get("getView", value);
      };

      /*
      */


      Adapter.prototype._get = function(method, value) {
        var adapter, result, _i, _len, _ref;

        _ref = this._adapters;
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          adapter = _ref[_i];
          result = adapter[method].call(adapter, value);
          if (result != null) {
            return result;
          }
        }
        return value;
      };

      return Adapter;

    })();
  });

}).call(this);
