// Generated by CoffeeScript 1.6.3
var BaseViewDecorator, DroppableDecorator, droppables, _ref,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

BaseViewDecorator = require("../base");

droppables = require("./collection");

DroppableDecorator = (function(_super) {
  __extends(DroppableDecorator, _super);

  function DroppableDecorator() {
    _ref = DroppableDecorator.__super__.constructor.apply(this, arguments);
    return _ref;
  }

  /*
  */


  DroppableDecorator.prototype.init = function() {
    DroppableDecorator.__super__.init.call(this);
    return this.name = this.view.droppable;
  };

  /*
  */


  DroppableDecorator.prototype.display = function() {
    return droppables.add(this.name, this);
  };

  /*
  */


  DroppableDecorator.prototype.remove = function() {
    return droppables.remove(this.name, this);
  };

  return DroppableDecorator;

})(BaseViewDecorator);

DroppableDecorator.getOptions = function(view) {
  return view.droppable;
};

module.exports = DroppableDecorator;
