// Generated by CoffeeScript 1.6.2
(function() {
  define(function() {
    var Base;

    return Base = (function() {
      /*
      */
      function Base(options) {
        this.options = options;
      }

      /*
       creates a new item
      */


      Base.prototype.createItem = function(options) {};

      return Base;

    })();
  });

}).call(this);
