// Generated by CoffeeScript 1.6.2
define(function() {
  var Base;

  return Base = (function() {
    /*
    */
    function Base(options) {
      this.options = options;
    }

    /*
     creates a new item
    */


    Base.prototype.createItem = function(options) {};

    return Base;

  })();
});
