// Generated by CoffeeScript 1.6.2
(function() {
  var __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define(["../../i18n/translate", "./base"], function(t, BaseTemplatePlugin) {
    /*
    */

    var I18NPlugin, _ref;

    return I18NPlugin = (function(_super) {
      __extends(I18NPlugin, _super);

      function I18NPlugin() {
        this.templateHelper = __bind(this.templateHelper, this);        _ref = I18NPlugin.__super__.constructor.apply(this, arguments);
        return _ref;
      }

      /*
      */


      I18NPlugin.prototype.templateHelper = function() {
        return {
          name: "i",
          render: function(text) {
            return t(text);
          }
        };
      };

      return I18NPlugin;

    })(BaseTemplatePlugin);
  });

}).call(this);
