// Generated by CoffeeScript 1.6.2
(function() {
  var BaseView, DecorFactory;

  BaseView = require("./base");

  DecorFactory = require("./decor/factory");

  module.exports = BaseView;

}).call(this);
