// Generated by CoffeeScript 1.6.2
(function() {
  module.exports = {
    NONE: "none",
    LOADING: "load",
    RENDERING: "render",
    DISPLAYING: "display",
    REMOVING: "remove"
  };

}).call(this);
