// Generated by CoffeeScript 1.6.2
(function() {
  define(["dojo-bootstrap/lib/templates/factory"], function(Templates) {
    var templates;

    templates = new Templates({
      directory: "/tpl",
      extension: "tpl.html"
    });
    return {
      helloWorld: {
        index: templates.get("helloWorld/index"),
        person: templates.get("helloWorld/person")
      }
    };
  });

}).call(this);
