


define(["require"], function(require) {

    var __dirname = "modules/mojo/interm/views/decor",
    __filename    = "modules/mojo/interm/views/decor/base.js",
    module        = { exports: {} },
    exports       = module.exports,
    define        = undefined,
    window        = exports,
    global        = window;

    

    // Generated by CoffeeScript 1.6.2
(function() {
  var ViewDecorator;

  ViewDecorator = (function() {
    /*
    */
    function ViewDecorator(view, options) {
      this.view = view;
      this.options = options;
      this.init();
    }

    /*
    */


    ViewDecorator.prototype.init = function() {};

    /*
     disposes immediatly without the teardown
    */


    ViewDecorator.prototype.dispose = function() {};

    return ViewDecorator;

  })();

  module.exports = ViewDecorator;

}).call(this);


    return module.exports;
});