


define(["require", "modules/mojo/interm/views/decor/base"], function(require) {

    var __dirname = "modules/mojo/interm/views/decor",
    __filename    = "modules/mojo/interm/views/decor/preload.js",
    module        = { exports: {} },
    exports       = module.exports,
    define        = undefined,
    window        = exports,
    global        = window;

    

    // Generated by CoffeeScript 1.6.2
(function() {
  var BaseDecor, PreloadDecorator, _ref,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  BaseDecor = require("modules/mojo/interm/views/decor/base");

  /*
   preloads a model, or set of models before
  */


  PreloadDecorator = (function(_super) {
    __extends(PreloadDecorator, _super);

    function PreloadDecorator() {
      _ref = PreloadDecorator.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    /*
    */


    PreloadDecorator.prototype.load = function(next) {
      var model, _ref1;

      model = (_ref1 = this.view.get("model")) != null ? _ref1 : this.view.get("item");
      if (!model || !(model != null ? model.fetch : void 0)) {
        return next();
      }
      return model.fetch(next);
    };

    return PreloadDecorator;

  })(BaseDecor);

  PreloadDecorator.getOptions = function(view) {
    return view.preload;
  };

  module.exports = BaseDecor;

}).call(this);


    return module.exports;
});