// Generated by CoffeeScript 1.6.2
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define(["bindable", "outcome"], function(bindable, outcome) {
    var ModelLocator, _ref;

    outcome.logAllErrors(true);
    /*
     core model locator should be vanilla so that the application has the ability to override
     these values
    */

    ModelLocator = (function(_super) {
      __extends(ModelLocator, _super);

      function ModelLocator() {
        _ref = ModelLocator.__super__.constructor.apply(this, arguments);
        return _ref;
      }

      return ModelLocator;

    })(bindable.Object);
    return new ModelLocator();
  });

}).call(this);
