// Generated by CoffeeScript 1.6.3
var ModelLocator, bindable, outcome, _ref,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

bindable = require("bindable");

outcome = require("outcome");

outcome.logAllErrors(true);

/*
 core model locator should be vanilla so that the application has the ability to override
 these values
*/


ModelLocator = (function(_super) {
  __extends(ModelLocator, _super);

  function ModelLocator() {
    _ref = ModelLocator.__super__.constructor.apply(this, arguments);
    return _ref;
  }

  return ModelLocator;

})(bindable.Object);

module.exports = new ModelLocator();
