// Generated by CoffeeScript 1.6.3
var ABTestFactory, factoryFactory;

factoryFactory = require("./factory");

ABTestFactory = (function() {
  /*
  */

  function ABTestFactory(control, tests) {
    this.factory = factoryFactory.create(control.choose(tests));
  }

  /*
  */


  ABTestFactory.prototype.create = function(item) {
    return this.factory.create;
  };

  return ABTestFactory;

})();

module.exports = ABTestFactory;
