// Generated by CoffeeScript 1.4.0
(function() {

  define(["./factory"], function(factoryFactory) {
    var ABTestFactory;
    return ABTestFactory = (function() {
      /*
      */

      function ABTestFactory(control, tests) {
        this.factory = factoryFactory.createItem(control.choose(tests));
      }

      /*
      */


      ABTestFactory.prototype.createItem = function(item) {
        return this.factory.createItem;
      };

      return ABTestFactory;

    })();
  });

}).call(this);
