// Generated by CoffeeScript 1.6.3
var Base;

Base = (function() {
  /*
  */

  function Base(options) {
    this.options = options;
  }

  /*
   creates a new item
  */


  Base.prototype.create = function(options) {};

  return Base;

})();

module.exports = Base;
