// Generated by CoffeeScript 1.6.3
var FnFactory;

FnFactory = (function() {
  /*
  */

  function FnFactory(create) {
    this.create = create;
  }

  return FnFactory;

})();

module.exports = FnFactory;
