// Generated by CoffeeScript 1.6.2
(function() {
  define(["./views/index", "./mediator/index"], function(View, mediator) {
    return {
      View: View,
      mediator: mediator
    };
  });

}).call(this);
