// Generated by CoffeeScript 1.6.3
var View, bindable, mediator, models;

View = require("./views");

mediator = require("./mediator");

bindable = require("bindable");

models = require("./models");

module.exports = {
  View: View,
  mediator: mediator,
  bindable: bindable,
  models: models,
  decorator: View.decorator,
  use: function(plugin) {
    return plugin(module.exports);
  }
};

module.exports.use(require("mojo-paperclip"));

if (typeof window !== "undefined") {
  window.mojo = module.exports;
}
