// Generated by CoffeeScript 1.6.3
var Application, View;

View = require("./views");

Application = require("./application");

module.exports = {
  View: View,
  Application: Application
};

if (typeof window !== "undefined") {
  window.mojo = module.exports;
}
