


define(["require", "modules/mojo/interm/views/base", "modules/mojo/interm/views/decor/factory"], function(require) {

    var __dirname = "modules/mojo/interm/views",
    __filename    = "modules/mojo/interm/views/index.js",
    module        = { exports: {} },
    exports       = module.exports,
    define        = undefined,
    window        = exports,
    global        = window;

    

    // Generated by CoffeeScript 1.6.2
(function() {
  var BaseView, DecorFactory;

  BaseView = require("modules/mojo/interm/views/base");

  DecorFactory = require("modules/mojo/interm/views/decor/factory");

  module.exports = BaseView;

}).call(this);


    return module.exports;
});