


define(["require"], function(require) {

    var __dirname = "modules/mojo/interm/views",
    __filename    = "modules/mojo/interm/views/states.js",
    module        = { exports: {} },
    exports       = module.exports,
    define        = undefined,
    window        = exports,
    global        = window;

    

    // Generated by CoffeeScript 1.6.2
(function() {
  module.exports = {
    NONE: "none",
    LOADING: "load",
    RENDERING: "render",
    DISPLAYING: "display",
    REMOVING: "remove"
  };

}).call(this);


    return module.exports;
});