// Generated by CoffeeScript 1.6.2
/*
  list:
    "selector": 
      childView: ChildView
      source: "someSource"
      transform: () ->
*/


(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define(["../base", "./list", "../../collection", "../../../utils/async", "../../../utils/idGenerator"], function(BaseDecorator, List, ViewCollection, async, generateId) {
    var ListDecorator, _ref;

    ListDecorator = (function(_super) {
      __extends(ListDecorator, _super);

      function ListDecorator() {
        _ref = ListDecorator.__super__.constructor.apply(this, arguments);
        return _ref;
      }

      /*
      */


      ListDecorator.prototype.init = function() {
        var list, lists, _i, _len, _results;

        ListDecorator.__super__.init.call(this);
        this._collection = new ViewCollection(lists = this._setupLists(this.view.list));
        _results = [];
        for (_i = 0, _len = lists.length; _i < _len; _i++) {
          list = lists[_i];
          _results.push(this.view.emit("list", list));
        }
        return _results;
      };

      /*
      */


      ListDecorator.prototype.load = function(callback) {
        return this._collection.load(callback);
      };

      /*
      */


      ListDecorator.prototype.render = function(callback) {
        return this._collection.render(callback);
      };

      /*
      */


      ListDecorator.prototype.display = function(callback) {
        return this._collection.display(callback);
      };

      /*
      */


      ListDecorator.prototype.remove = function(callback) {
        return this._collection.remove(callback);
      };

      /*
      */


      ListDecorator.prototype._setupLists = function(lists) {
        var key, keyParts, list, property, selector, _lists;

        if (this._isSingle(lists)) {
          return [new List(generateId(), this.view, lists.selector || this.view.el, lists)];
        }
        _lists = [];
        for (key in lists) {
          keyParts = key.split(" ");
          selector = keyParts.pop();
          property = keyParts.pop();
          list = new List(property || selector, this.view, selector, lists[key]);
          if (property) {
            this.view[property] = list;
          }
          _lists.push(list);
        }
        return _lists;
      };

      /*
      */


      ListDecorator.prototype._isSingle = function(list) {
        var key;

        for (key in list) {
          if (typeof list[key] !== "object") {
            return true;
          }
        }
        return false;
      };

      return ListDecorator;

    })(BaseDecorator);
    ListDecorator.test = function(view) {
      return !!view.list;
    };
    return ListDecorator;
  });

}).call(this);
