// Generated by CoffeeScript 1.4.0
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define(["bindable"], function(Bindable) {
    /*
       core model locator should be vanilla so that the application has the ability to override
       these values
    */

    var ModelLocator;
    ModelLocator = (function(_super) {

      __extends(ModelLocator, _super);

      function ModelLocator() {
        return ModelLocator.__super__.constructor.apply(this, arguments);
      }

      return ModelLocator;

    })(Bindable);
    return new ModelLocator();
  });

}).call(this);
