// Generated by CoffeeScript 1.6.2
(function() {
  define(["type-component"], function(type) {
    var ChildSection;

    ChildSection = (function() {
      function ChildSection(parentView, name, viewClass) {
        this.parentView = parentView;
        this.name = name;
        this.viewClass = viewClass;
        this.view = new this.viewClass();
        this.parentView.linkChild(this.view);
      }

      ChildSection.prototype.load = function(next) {
        return this.view.load(next);
      };

      ChildSection.prototype.render = function(next) {
        return this.view.render(next);
      };

      ChildSection.prototype.display = function(next) {
        return this.view.display(next);
      };

      ChildSection.prototype.remove = function(next) {
        return this.view.remove(next);
      };

      ChildSection.prototype.toString = function() {
        return this.view.section.toString();
      };

      ChildSection.test = function(options) {
        return type(options) === "function";
      };

      return ChildSection;

    })();
    return ChildSection;
  });

}).call(this);
