// Generated by CoffeeScript 1.6.3
var ChildSection, type;

type = require("type-component");

ChildSection = (function() {
  function ChildSection(parentView, name, viewOrClass) {
    this.parentView = parentView;
    this.name = name;
    this.view = viewOrClass.__isView ? viewOrClass : new viewOrClass();
    this.parentView.linkChild(this.view);
  }

  ChildSection.prototype.load = function(next) {
    return this.view.load(next);
  };

  ChildSection.prototype.render = function(next) {
    return this.view.render(next);
  };

  ChildSection.prototype.display = function(next) {
    return this.view.display(next);
  };

  ChildSection.prototype.remove = function(next) {
    return this.view.remove(next);
  };

  ChildSection.prototype.toString = function() {
    this.rendered = true;
    return this.view.section.toString();
  };

  ChildSection.test = function(options) {
    return (type(options) === "function") || options.__isView;
  };

  return ChildSection;

})();

module.exports = ChildSection;
