// Generated by CoffeeScript 1.6.3
var views;

views = require("../views");

module.exports = function(mojo) {
  return mojo.registerClass({
    "views.list": views.ListView,
    "views.states": views.StatesView
  });
};
