// Generated by CoffeeScript 1.6.3
var views;

views = require("../views");

module.exports = function(app) {
  return app.registerClass({
    "views.list": views.ListView,
    "views.states": views.StatesView
  });
};
