// Generated by CoffeeScript 1.6.2
(function() {
  var views;

  views = require("../views");

  module.exports = function(app) {
    app.registerViewClass("list", views.ListView);
    app.registerViewClass("states", views.StatesView);
    return app.registerViewClass("base", views.BaseView);
  };

}).call(this);
