// Generated by CoffeeScript 1.6.2
define([], function() {
  return function() {
    var biggest, count, counts, fn, fns, key;

    count = 0;
    fn = arguments.callee;
    counts = {};
    while ((fn = fn.caller) && count < 10000) {
      fns = String(fn);
      counts[fns] = counts[fns] != null ? counts[fns] + 1 : 1;
      count++;
    }
    console.log("stack");
    console.log(Object.keys(counts).length);
    biggest = null;
    for (key in counts) {
      if (!biggest) {
        biggest = key;
        continue;
      }
      if (counts[key] > counts[biggest]) {
        key = biggest;
      }
    }
    console.log(counts[biggest], biggest);
    console.log("end stack");
    return count;
  };
});
