// Generated by CoffeeScript 1.6.2
(function() {
  define(function() {
    var key, logger, _i, _len, _ref, _results,
      _this = this;

    logger = {};
    _ref = ["log", "warn", "error"];
    _results = [];
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      key = _ref[_i];
      _results.push((function(key) {
        return logger[key] = function() {
          var args;

          args = Array.prototype.slice.call(arguments);
          args[0] = "dojo-bootstrap: " + args[0];
          return console[key].apply(console, args);
        };
      })(key));
    }
    return _results;
  });

}).call(this);
