// Generated by CoffeeScript 1.6.2
define(function() {
  var ViewDecorator;

  return ViewDecorator = (function() {
    /*
    */
    function ViewDecorator(view, options) {
      this.view = view;
      this.options = options;
      this.init();
    }

    /*
    */


    ViewDecorator.prototype.init = function() {};

    /*
     disposes immediatly without the teardown
    */


    ViewDecorator.prototype.dispose = function() {};

    return ViewDecorator;

  })();
});
