// Generated by CoffeeScript 1.6.2
(function() {
  define(function() {
    var ViewDecorator;

    return ViewDecorator = (function() {
      /*
      */
      function ViewDecorator(view) {
        this.view = view;
        this.init();
      }

      /*
      */


      ViewDecorator.prototype.init = function() {};

      /*
       disposes immediatly without the teardown
      */


      ViewDecorator.prototype.dispose = function() {};

      return ViewDecorator;

    })();
  });

}).call(this);
