// Generated by CoffeeScript 1.6.2
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define(["./base", "rivets", "dref"], function(BaseViewDecorator, rivets, dref) {
    var BindingsDecorator, _ref;

    rivets.configure({
      adapter: {
        subscribe: function(obj, keypath, callback) {
          if (obj.on) {
            return obj.on("change:" + keypath.replace(/,/g, "."), callback);
          }
        },
        unsubscribe: function(obj, keypath, callback) {
          if (obj.on) {
            return obj.off("change:" + keypath.replace(/,/g, "."), callback);
          }
        },
        read: function(obj, keypath) {
          console.log(keypath, obj);
          return obj.get(keypath.replace(/,/g, "."));
        },
        publish: function(obj, keypath, value) {
          return obj.set(keypath.replace(/,/g, "."), value);
        }
      }
    });
    rivets.formatters.negate = function(value) {
      return !value;
    };
    BindingsDecorator = (function(_super) {
      __extends(BindingsDecorator, _super);

      function BindingsDecorator() {
        _ref = BindingsDecorator.__super__.constructor.apply(this, arguments);
        return _ref;
      }

      /*
      */


      BindingsDecorator.prototype.render = function(callback) {
        rivets.bind(this.view.el, {
          data: this.view
        });
        return callback();
      };

      return BindingsDecorator;

    })(BaseViewDecorator);
    BindingsDecorator.test = function(view) {
      return true;
    };
    return BindingsDecorator;
  });

}).call(this);
