// Generated by CoffeeScript 1.6.2
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define(["./base", "outcome", "../../utils/async", "../collection"], function(BaseViewDecorator, outcome, async, Collection) {
    var ChildrenDecorator, _ref;

    ChildrenDecorator = (function(_super) {
      __extends(ChildrenDecorator, _super);

      function ChildrenDecorator() {
        _ref = ChildrenDecorator.__super__.constructor.apply(this, arguments);
        return _ref;
      }

      /*
      */


      ChildrenDecorator.prototype.init = function() {
        var childrenClasses, clazz, property, selector, selectorParts, view, viewName, _results;

        ChildrenDecorator.__super__.init.call(this);
        childrenClasses = this.view.children;
        this._children = new Collection();
        _results = [];
        for (viewName in childrenClasses) {
          selectorParts = viewName.split(" ");
          property = selectorParts.shift();
          selector = selectorParts.shift() || property;
          clazz = childrenClasses[viewName];
          view = new clazz();
          this._children[property] = view;
          this.view.set(property, view);
          view.__selector = selector;
          _results.push(this._children.push(view));
        }
        return _results;
      };

      /*
      */


      ChildrenDecorator.prototype.load = function(callback) {
        this.view.children = this.view.children = this._children;
        return this._children.load(callback);
      };

      /*
      */


      ChildrenDecorator.prototype.render = function(callback) {
        var child, _i, _len, _ref1;

        _ref1 = this._children.source();
        for (_i = 0, _len = _ref1.length; _i < _len; _i++) {
          child = _ref1[_i];
          child.element(this.view.$(child.__selector));
        }
        return this._children.render(function() {
          return callback();
        });
      };

      /*
      */


      ChildrenDecorator.prototype.display = function(callback) {
        return this._children.display(callback);
      };

      /*
      */


      ChildrenDecorator.prototype.remove = function(callback) {
        return this._children.remove(callback);
      };

      return ChildrenDecorator;

    })(BaseViewDecorator);
    ChildrenDecorator.test = function(view) {
      return view.children && !view.children.__isCollection;
    };
    return ChildrenDecorator;
  });

}).call(this);
