// Generated by CoffeeScript 1.6.3
var InheritDecorator,
  __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

InheritDecorator = (function() {
  /*
  */

  function InheritDecorator(view, inherit) {
    this.view = view;
    this.inherit = inherit;
    this.render = __bind(this.render, this);
    view.once("render", this.render);
  }

  /*
  */


  InheritDecorator.prototype.render = function() {
    return console.log("INHERIT");
  };

  /*
  */


  InheritDecorator.getOptions = function(view) {
    return view.inherit;
  };

  InheritDecorator.decorate = function(view, inherit) {
    return new InheritDecorator(view, inherit);
  };

  return InheritDecorator;

})();

module.exports = InheritDecorator;
