// Generated by CoffeeScript 1.6.3
var PaperclipViewDecorator, paperclip, type;

paperclip = require("paperclip");

type = require("type-component");

PaperclipViewDecorator = (function() {
  /*
  */

  function PaperclipViewDecorator(view, template) {
    this.view = view;
    this.template = template;
    if (type(template) !== "function") {
      throw new Error("paper template must be a function for view \"" + this.view.constructor.name + "\"");
    }
    this.template = paperclip.template(this.template);
  }

  /*
  */


  PaperclipViewDecorator.prototype.load = function() {
    this.content = this.template.bind(this.view);
    return this.view.section.append(this.content.section.toFragment());
  };

  PaperclipViewDecorator.prototype.remove = function() {
    var e;
    try {
      return this.content.dispose();
    } catch (_error) {
      e = _error;
      console.error("unable to unbind paperclip template to " + (this._traceViewPath()));
      return console.error(e.stack || e);
    }
  };

  /*
  */


  PaperclipViewDecorator.prototype._traceViewPath = function() {
    var cv, path;
    path = [];
    cv = this.view;
    while (cv) {
      path.unshift(cv.constructor.name);
      cv = cv._parent;
    }
    return path.join(".");
  };

  /*
  */


  PaperclipViewDecorator.getOptions = function(view) {
    return view.paper;
  };

  return PaperclipViewDecorator;

})();

module.exports = PaperclipViewDecorator;
