// Generated by CoffeeScript 1.6.2
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define(["./base"], function(BaseDecor) {
    var PreloadDecorator, _ref;

    PreloadDecorator = (function(_super) {
      __extends(PreloadDecorator, _super);

      function PreloadDecorator() {
        _ref = PreloadDecorator.__super__.constructor.apply(this, arguments);
        return _ref;
      }

      /*
      */


      PreloadDecorator.prototype.load = function(next) {
        var model, _ref1;

        model = (_ref1 = this.view.get("model")) != null ? _ref1 : this.view.get("item");
        if (!model || !(model != null ? model.fetch : void 0)) {
          return next();
        }
        return model.fetch(next);
      };

      return PreloadDecorator;

    })(BaseDecor);
    PreloadDecorator.getOptions = function(view) {
      return view.preload;
    };
    return PreloadDecorator;
  });

}).call(this);
