


define(["require"], function(require) {

    var __dirname = "modules/mojo/interm/utils",
    __filename    = "modules/mojo/interm/utils/idGenerator.js",
    module        = { exports: {} },
    exports       = module.exports,
    define        = undefined,
    window        = exports,
    global        = window;

    

    // Generated by CoffeeScript 1.6.2
(function() {
  var i;

  i = 0;

  module.exports = function() {
    return i++;
  };

}).call(this);


    return module.exports;
});