// Generated by CoffeeScript 1.6.3
var ViewDecorator;

ViewDecorator = (function() {
  /*
  */

  function ViewDecorator(view, options) {
    this.view = view;
    this.options = options;
    this.init();
  }

  /*
  */


  ViewDecorator.prototype.init = function() {};

  return ViewDecorator;

})();

module.exports = ViewDecorator;
