// Generated by CoffeeScript 1.6.3
var BaseViewDecorator, DraggableDecorator, DroppableDecorator, EventsDecorator, PreloadDecorator, SectionsDecorator, SelectorDecorator, TransitionDecorator, decor;

BaseViewDecorator = require("./base");

SelectorDecorator = require("./selector");

EventsDecorator = require("./events");

SectionsDecorator = require("./sections/index");

DraggableDecorator = require("./dragdrop/draggable");

DroppableDecorator = require("./dragdrop/droppable");

TransitionDecorator = require("./transition");

PreloadDecorator = require("./preload");

decor = require("bindable-decor")();

decor.use(require("bindable-decor-bindings")("render"), SelectorDecorator, PreloadDecorator, TransitionDecorator, EventsDecorator, DraggableDecorator, DroppableDecorator, SectionsDecorator);

module.exports = decor;
