// Generated by CoffeeScript 1.6.3
var BaseViewDecorator, BindingsDecorator, DraggableDecorator, DroppableDecorator, EventsDecorator, PaperclipDecorator, PreloadDecorator, SectionsDecorator, SelectorDecorator, TransitionDecorator, decor;

BaseViewDecorator = require("./base");

SelectorDecorator = require("./selector");

PaperclipDecorator = require("./paperclip");

EventsDecorator = require("./events");

BindingsDecorator = require("./bindings");

SectionsDecorator = require("./sections/index");

DraggableDecorator = require("./dragdrop/draggable");

DroppableDecorator = require("./dragdrop/droppable");

TransitionDecorator = require("./transition");

PreloadDecorator = require("./preload");

decor = require("bindable-decor")();

decor.use(BindingsDecorator, SelectorDecorator, PreloadDecorator, {
  decorator: PaperclipDecorator,
  inheritable: false
}, TransitionDecorator, EventsDecorator, DraggableDecorator, DroppableDecorator, SectionsDecorator);

module.exports = decor;
