// Generated by CoffeeScript 1.6.3
var PaperclipViewDecorator, paperclip, type,
  __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

paperclip = require("paperclip");

type = require("type-component");

PaperclipViewDecorator = (function() {
  /*
  */

  function PaperclipViewDecorator(view, template) {
    this.view = view;
    this.template = template;
    this.remove = __bind(this.remove, this);
    this.render = __bind(this.render, this);
    if (type(template) !== "function") {
      throw new Error("paper template must be a function for view \"" + this.view.constructor.name + "\"");
    }
    this.template = paperclip.template(this.template);
    this.view.once("render", this.render);
    this.view.once("remove", this.remove);
  }

  /*
  */


  PaperclipViewDecorator.prototype.render = function() {
    this.content = this.template.bind(this.view);
    return this.view.section.append(this.content.section.toFragment());
  };

  /*
  */


  PaperclipViewDecorator.prototype.remove = function() {
    return this.content.unbind();
  };

  /*
  */


  PaperclipViewDecorator.getOptions = function(view) {
    return view.paper;
  };

  return PaperclipViewDecorator;

})();

module.exports = PaperclipViewDecorator;
