// Generated by CoffeeScript 1.4.0
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define(["./base"], function(Base) {
    var VanillaEngine;
    return VanillaEngine = (function(_super) {

      __extends(VanillaEngine, _super);

      function VanillaEngine() {
        VanillaEngine.__super__.constructor.call(this, "tpl");
      }

      /*
      */


      VanillaEngine.prototype.compile = function(source) {
        return {
          render: function(options, callback) {
            return callback(null, source);
          }
        };
      };

      return VanillaEngine;

    })(Base);
  });

}).call(this);
