// Generated by CoffeeScript 1.6.2
(function() {
  var BaseFactory, ClassFactory, factoryFactory,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  BaseFactory = require("./base");

  factoryFactory = require("./factory");

  ClassFactory = (function(_super) {
    __extends(ClassFactory, _super);

    /*
    */


    function ClassFactory(clazz, _test) {
      this.clazz = clazz;
      this._test = _test;
    }

    /*
    */


    ClassFactory.prototype.test = function(item) {
      if (this.clazz.test) {
        return this.clazz.test(item);
      }
      if (this._test) {
        return this._test(item);
      }
      return true;
    };

    /*
    */


    ClassFactory.prototype.create = function(options) {
      return new this.clazz(options);
    };

    return ClassFactory;

  })(BaseFactory);

  ClassFactory.test = function(item) {
    return (typeof item === "function") && item.prototype;
  };

  factoryFactory.addFactoryClass(ClassFactory);

  module.exports = ClassFactory;

}).call(this);
