// Generated by CoffeeScript 1.6.2
(function() {
  define([], function() {
    var FnFactory;

    return FnFactory = (function() {
      /*
      */
      function FnFactory(create) {
        this.create = create;
      }

      return FnFactory;

    })();
  });

}).call(this);
