// Generated by CoffeeScript 1.4.0
(function() {

  define(function() {
    var ViewDecorator;
    return ViewDecorator = (function() {
      /*
      */

      function ViewDecorator(view) {
        this.view = view;
        this.init();
      }

      /*
      */


      ViewDecorator.prototype.init = function() {};

      /*
      */


      ViewDecorator.prototype.load = function(callback) {
        return callback();
      };

      /*
           called when the view is added to an element
      */


      ViewDecorator.prototype.attach = function(callback) {
        return callback();
      };

      /*
           called when a view is removed
      */


      ViewDecorator.prototype.remove = function(callback) {
        return callback();
      };

      /*
           disposes immediatly without the teardown
      */


      ViewDecorator.prototype.dispose = function() {};

      return ViewDecorator;

    })();
  });

}).call(this);
