


define(["require"], function(require) {

    var __dirname = "modules/mojo/interm/factories",
    __filename    = "modules/mojo/interm/factories/base.js",
    module        = { exports: {} },
    exports       = module.exports,
    define        = undefined,
    window        = exports,
    global        = window;

    

    // Generated by CoffeeScript 1.6.2
(function() {
  var Base;

  Base = (function() {
    /*
    */
    function Base(options) {
      this.options = options;
    }

    /*
     creates a new item
    */


    Base.prototype.create = function(options) {};

    return Base;

  })();

  module.exports = Base;

}).call(this);


    return module.exports;
});