


define(["require"], function(require) {

    var __dirname = "modules/mojo/interm/factories",
    __filename    = "modules/mojo/interm/factories/fn.js",
    module        = { exports: {} },
    exports       = module.exports,
    define        = undefined,
    window        = exports,
    global        = window;

    

    // Generated by CoffeeScript 1.6.2
(function() {
  var FnFactory;

  FnFactory = (function() {
    /*
    */
    function FnFactory(create) {
      this.create = create;
    }

    return FnFactory;

  })();

  module.exports = FnFactory;

}).call(this);


    return module.exports;
});