// Generated by CoffeeScript 1.6.2
(function() {
  var Base, Handlebars, HandlebarsEngine, i18n, _ref,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  Base = require("./base");

  Handlebars = require("handlebars");

  i18n = require("i18next");

  HandlebarsEngine = (function(_super) {
    __extends(HandlebarsEngine, _super);

    function HandlebarsEngine() {
      _ref = HandlebarsEngine.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    HandlebarsEngine.prototype.extension = "hb";

    /*
    */


    HandlebarsEngine.prototype.init = function() {
      return Handlebars.registerHelper("t", function(i18key) {
        return new Handlebars.SafeString(i18n.t(i18key));
      });
    };

    /*
    */


    HandlebarsEngine.prototype.compile = function(source) {
      var template;

      template = Handlebars.compile(source);
      return {
        render: function(options, callback) {
          return callback(null, template(options));
        }
      };
    };

    return HandlebarsEngine;

  })(Base);

  module.exports = HandlebarsEngine;

}).call(this);
