// Generated by CoffeeScript 1.6.3
var Section, SectionsDecorator, ViewCollection, type;

Section = require("./section");

type = require("type-component");

ViewCollection = require("../../collection");

SectionsDecorator = (function() {
  /*
  */

  function SectionsDecorator(view, sectionOptions) {
    this.view = view;
    this.sectionOptions = sectionOptions;
    this._views = new ViewCollection();
    this.init();
  }

  /*
  */


  SectionsDecorator.prototype.load = function(next) {
    return this._views.load(next);
  };

  SectionsDecorator.prototype.render = function(next) {
    return this._views.render(next);
  };

  SectionsDecorator.prototype.display = function(next) {
    return this._views.display(next);
  };

  SectionsDecorator.prototype.remove = function(next) {
    return this._views.remove(next);
  };

  /*
  */


  SectionsDecorator.prototype.init = function() {
    var sectionName, _results;
    _results = [];
    for (sectionName in this.sectionOptions) {
      _results.push(this._addSection(sectionName, this.sectionOptions[sectionName]));
    }
    return _results;
  };

  /*
  */


  SectionsDecorator.prototype._addSection = function(name, options) {
    return this.view.set("sections." + name, new Section(this, name, this._getSectionClass(options), options));
  };

  /*
  */


  SectionsDecorator.prototype._initialized = function(section) {
    return this._views.push(section.view);
  };

  /*
  */


  SectionsDecorator.prototype._getSectionClass = function(options) {
    if (type(options) === "function") {
      return options;
    } else {
      return this.view.get("models.components." + options.type);
    }
  };

  /*
  */


  SectionsDecorator.getOptions = function(view) {
    return view.sections;
  };

  return SectionsDecorator;

})();

module.exports = SectionsDecorator;
