// Generated by CoffeeScript 1.6.3
var SectionsDecorator, type;

type = require("type-component");

SectionsDecorator = (function() {
  /*
  */

  function SectionsDecorator(view, sectionOptions) {
    this.view = view;
    this.sectionOptions = sectionOptions;
    this.view.set("sections", {});
    this.init();
  }

  /*
  */


  SectionsDecorator.prototype.init = function() {
    var sectionName, _results;
    _results = [];
    for (sectionName in this.sectionOptions) {
      _results.push(this._addSection(sectionName, this.sectionOptions[sectionName]));
    }
    return _results;
  };

  /*
  */


  SectionsDecorator.prototype._addSection = function(name, options) {
    var view, viewClass,
      _this = this;
    viewClass = this._getSectionClass(options);
    view = new viewClass(options);
    view._parent = this.view;
    view.once("initialize", function() {
      return view.decorate(options);
    });
    view.createFragment = function() {
      if (view._createdFragment) {
        return view.section.toFragment();
      }
      view._createdFragment = true;
      _this.view.callstack.unshift(view.render);
      return view.section.toFragment();
    };
    return this.view.set("sections." + name, view);
  };

  /*
  */


  SectionsDecorator.prototype._getSectionClass = function(options) {
    var t;
    if (!options.type) {
      options = {
        type: options
      };
    }
    if ((t = type(options.type)) === "function") {
      return options.type;
    } else if (t === "string") {
      return this.view.get("models.components." + options.type);
    } else {
      throw new Error("cannot get section class for type " + t);
    }
  };

  /*
  */


  SectionsDecorator.getOptions = function(view) {
    return view.sections;
  };

  SectionsDecorator.decorate = function(view, options) {
    return new SectionsDecorator(view, options);
  };

  return SectionsDecorator;

})();

module.exports = SectionsDecorator;
