// Generated by CoffeeScript 1.6.3
var Section, dref,
  __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

dref = require("dref");

Section = (function(_super) {
  __extends(Section, _super);

  /*
  */


  function Section(sections, name, viewClass, options) {
    this.sections = sections;
    this.name = name;
    this.viewClass = viewClass;
    this.options = options;
    this._onChange = __bind(this._onChange, this);
    Section.__super__.constructor.call(this, options);
    this.on("change", this._onChange);
  }

  /*
  */


  Section.prototype.createFragment = function() {
    if (!this.view) {
      this.view = new this.viewClass();
      this.view.set(this.data);
      this.view._parent = this.sections.view;
      this.sections.view.callstack.unshift(this.view.render);
    }
    return this.view.section.toFragment();
  };

  /*
  */


  Section.prototype._onChange = function(key, value) {
    var _ref;
    return (_ref = this.view) != null ? _ref.set(key, value) : void 0;
  };

  return Section;

})(require("bindable").Object);

module.exports = Section;
