// Generated by CoffeeScript 1.6.2
(function() {
  var __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define(["bindable", "stepc"], function(bindable, stepc) {
    var States;

    return States = (function(_super) {
      __extends(States, _super);

      /*
      */


      function States(decorator, options) {
        this.decorator = decorator;
        this.options = options;
        this._displayView = __bind(this._displayView, this);
        this._renderView = __bind(this._renderView, this);
        this._setIndex = __bind(this._setIndex, this);
        this.prev = __bind(this.prev, this);
        this.next = __bind(this.next, this);
        States.__super__.constructor.call(this);
        this._id = this.name = this.options.name;
        this.view = decorator.view;
        this.views = new bindable.Collection();
        this.views.enforceId(false);
        this.views.reset(this.options.views || this.options);
        this.set("index", this.options.index || 0);
        this.selector = this.options.selector;
        this.rotate = this.options.rotate || false;
      }

      /*
      */


      States.prototype.load = function(callback) {
        this.once("loadedState", callback);
        return this.bind("index", this._setIndex);
      };

      /*
      */


      States.prototype.render = function(callback) {
        this.once("renderedState", callback);
        return this.bind("currentView", this._renderView);
      };

      /*
      */


      States.prototype.display = function(callback) {
        this.once("displayedState", callback);
        return this.bind("currentView", this._displayView);
      };

      /*
      */


      States.prototype.remove = function(callback) {
        if (!this._currentView) {
          return callback();
        }
        return this._currentView.remove(callback);
      };

      /*
      */


      States.prototype.next = function() {
        var newIndex;

        newIndex = this.get("index") + 1;
        if (newIndex >= this.views.length()) {
          if (this.rotate) {
            newIndex = 0;
          } else {
            newIndex = this.views.length() - 1;
            this.emit("ended");
          }
        }
        return this.set("index", newIndex);
      };

      /*
      */


      States.prototype.prev = function() {
        var newIndex;

        newIndex = this.get("index") - 1;
        if (newIndex < 0) {
          if (this.rotate) {
            newIndex = this.views.length() - 1;
          } else {
            newIndex = 0;
          }
        }
        return this.set("index", newIndex);
      };

      /*
      */


      States.prototype._setIndex = function(index) {
        var newState, newStatesClass, self;

        if (!this.views.length()) {
          return;
        }
        self = this;
        newStatesClass = this.views.at(index || 0);
        newState = new newStatesClass();
        return stepc.async((function() {
          return newState.loadables.load(this);
        }), (function() {
          if (!self._currentView) {
            return this();
          }
          return self._currentView.remove(this);
        }), (function() {
          self._currentView = newState;
          self.set("currentView", newState);
          return self.emit("loadedState");
        }));
      };

      /*
      */


      States.prototype._renderView = function(view) {
        var _this = this;

        view.element(this._element());
        return view.render(function() {
          return _this.emit("renderedState");
        });
      };

      /*
      */


      States.prototype._displayView = function(view) {
        var _this = this;

        return view.display(function() {
          return _this.emit("displayedState");
        });
      };

      /*
      */


      States.prototype._element = function() {
        if (this.selector) {
          return this.view.$(this.selector);
        } else {
          return this.view.el;
        }
      };

      return States;

    })(bindable.Object);
  });

}).call(this);
