// Generated by CoffeeScript 1.6.2
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define(["bindable", "underscore"], function(bindable, _) {
    return (function(_super) {
      __extends(_Class, _super);

      /*
      */


      function _Class(states, options) {
        var ops;

        this.states = states;
        ops = {};
        if (!options["class"]) {
          ops["class"] = options;
        } else {
          ops = options;
        }
        this._id = options.name || Math.random();
        _Class.__super__.constructor.call(this, ops);
      }

      /*
      */


      _Class.prototype.createView = function() {
        var clazz;

        clazz = this.get("class");
        return new clazz();
      };

      return _Class;

    })(bindable.Object);
  });

}).call(this);
