// Generated by CoffeeScript 1.6.2
(function() {
  var __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define(["../list", "./base", "../base", "../../templates/factory", "dref", "bindable"], function(ListView, InputView, View, templates, dref, bindable) {
    var SelectInputView, _ref;

    return SelectInputView = (function(_super) {
      __extends(SelectInputView, _super);

      function SelectInputView() {
        this._onValueChanged = __bind(this._onValueChanged, this);
        this.select = __bind(this.select, this);
        this.transformSourceItem = __bind(this.transformSourceItem, this);        _ref = SelectInputView.__super__.constructor.apply(this, arguments);
        return _ref;
      }

      /*
      */


      SelectInputView.prototype.template = templates.fromSource("<select name='{{view.name}}'></select>", {
        engine: "handlebars"
      });

      /*
      */


      SelectInputView.prototype.childrenElement = "select";

      /*
      */


      SelectInputView.prototype.childTemplate = templates.fromSource("<option value='{{value}}'>{{label}}</option>", {
        engine: "handlebars"
      });

      /*
      */


      SelectInputView.prototype.selectLabel = "Select";

      /*
      */


      SelectInputView.prototype.itemLabel = "label";

      /*
      */


      SelectInputView.prototype.itemValue = "_id";

      /*
      */


      SelectInputView.prototype.childViewClass = View;

      /*
      */


      SelectInputView.prototype.transformSourceItem = function(item) {
        return {
          _id: dref.get(item, "_id"),
          value: dref.get(item, this.get("itemValue")) || dref.get(item, this.get("itemLabel")),
          label: dref.get(item, this.get("itemLabel")),
          data: item
        };
      };

      /*
      */


      SelectInputView.prototype.init = function() {
        SelectInputView.__super__.init.call(this);
        return this.children = new bindable.Collection([
          new View({
            label: this.get("selectLabel")
          })
        ]);
      };

      /*
      */


      SelectInputView.prototype.events = {
        "change select": function(event) {
          var selected, selectedVal;

          selected = this.$(":selected");
          selectedVal = selected.val();
          if (!selectedVal.length) {
            return this.deselect();
          }
          return this.select(selected.index() - 1);
        }
      };

      /*
       Selects an item based on the index
      */


      SelectInputView.prototype.select = function(index) {
        if (!~index) {
          return this.deselect();
        }
        return this.set("value", this.get("source").at(index).value);
      };

      /*
       deselects the item
      */


      SelectInputView.prototype.deselect = function() {
        return this.set("value", void 0);
      };

      /*
      */


      SelectInputView.prototype._onValueChanged = function(value) {
        var i, index, item, _i, _len, _ref1;

        SelectInputView.__super__._onValueChanged.call(this);
        index = -1;
        _ref1 = this.source.source();
        for (i = _i = 0, _len = _ref1.length; _i < _len; i = ++_i) {
          item = _ref1[i];
          if (item.value === value) {
            index = i;
            break;
          }
        }
        if (!~index) {
          return;
        }
        return this.$("select").children().eq(index).attr("selected", "selected");
      };

      return SelectInputView;

    })(InputView);
  });

}).call(this);
