// Generated by CoffeeScript 1.6.3
var BaseView, TextInputView, templates, textTemplate, _ref,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

BaseView = require("./base");

templates = require("../../templates/factory");

textTemplate = require("./text.pc");

TextInputView = (function(_super) {
  __extends(TextInputView, _super);

  function TextInputView() {
    _ref = TextInputView.__super__.constructor.apply(this, arguments);
    return _ref;
  }

  /*
  */


  TextInputView.prototype.paper = textTemplate;

  return TextInputView;

})(BaseView);

module.exports = TextInputView;
