// Generated by CoffeeScript 1.6.3
var EventsDecorator, janitor,
  __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

janitor = require("janitorjs");

EventsDecorator = (function() {
  /*
  */

  function EventsDecorator(view, options) {
    this.view = view;
    this.options = options;
    this.remove = __bind(this.remove, this);
    this.render = __bind(this.render, this);
    this.events = this.options;
    this.view.once("render", this.render);
    this.view.once("dispose", this.remove);
  }

  /*
  */


  EventsDecorator.prototype.render = function() {
    var e, selector, _results;
    e = this._events();
    this._disposeBindings();
    this._janitor = janitor();
    _results = [];
    for (selector in e) {
      _results.push(this._addBinding(selector, e[selector]));
    }
    return _results;
  };

  /*
  */


  EventsDecorator.prototype.remove = function() {
    return this._disposeBindings();
  };

  /*
  */


  EventsDecorator.prototype._addBinding = function(selector, viewMethod) {
    var action, actions, cb, elements, lowerActions, selectorParts, selectors, _fn, _i, _len, _ref,
      _this = this;
    selectorParts = selector.split(" ");
    actions = selectorParts.shift().split(/\|/g).join(" ");
    selectors = selectorParts.join(",");
    cb = function() {
      var ref;
      if (typeof viewMethod === "function") {
        ref = viewMethod;
      } else {
        ref = _this.view.get(viewMethod);
      }
      return ref.apply(_this.view, arguments);
    };
    if (!selectors.length) {
      elements = this.view.$();
    } else {
      elements = this.view.$(selectors);
    }
    elements.bind(lowerActions = actions.toLowerCase(), cb);
    _ref = lowerActions.split(" ");
    _fn = function(action) {
      return _this._janitor.add(_this.view.on(action, function() {
        return cb.apply(this, [$.Event(action)].concat(Array.prototype.slice.call(arguments)));
      }));
    };
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      action = _ref[_i];
      _fn(action);
    }
    return this._janitor.add(function() {
      return elements.unbind(lowerActions, cb);
    });
  };

  /*
  */


  EventsDecorator.prototype._disposeBindings = function() {
    if (!this._janitor) {
      return;
    }
    this._janitor.dispose();
    return this._janitor = void 0;
  };

  /*
  */


  EventsDecorator.prototype._events = function() {
    return this.events;
  };

  /*
  */


  EventsDecorator.priority = "display";

  EventsDecorator.getOptions = function(view) {
    return view.events;
  };

  EventsDecorator.decorate = function(view, options) {
    return new EventsDecorator(view, options);
  };

  return EventsDecorator;

})();

module.exports = EventsDecorator;
