// Generated by CoffeeScript 1.6.3
var BaseViewDecorator, EventsDecorator, SectionsDecorator, bindableDecor, bindableDecorbindings;

BaseViewDecorator = require("./base");

EventsDecorator = require("./events");

SectionsDecorator = require("./sections/index");

bindableDecor = require("bindable-decor");

bindableDecorbindings = require("bindable-decor-bindings");

module.exports = function(app) {
  var decor;
  decor = bindableDecor();
  decor.priority("load", 0).priority("render", 1).priority("display", 2).use(bindableDecorbindings("render"), EventsDecorator, SectionsDecorator);
  app.decorators = decor;
  return app.decorator = function(decorator) {
    return decor.use(decorator);
  };
};
