// Generated by CoffeeScript 1.6.3
var BaseViewDecorator, DraggableDecorator, DroppableDecorator, EventsDecorator, SectionsDecorator, TransitionDecorator, bindableDecor, bindableDecorbindings;

BaseViewDecorator = require("./base");

EventsDecorator = require("./events");

SectionsDecorator = require("./sections/index");

DraggableDecorator = require("./dragdrop/draggable");

DroppableDecorator = require("./dragdrop/droppable");

TransitionDecorator = require("./transition");

bindableDecor = require("bindable-decor");

bindableDecorbindings = require("bindable-decor-bindings");

module.exports = function(app) {
  var decor;
  decor = bindableDecor();
  decor.priority("load", 0).priority("render", 1).priority("display", 2).use(bindableDecorbindings("render"), TransitionDecorator, EventsDecorator, DraggableDecorator, DroppableDecorator, SectionsDecorator);
  app.decorators = decor;
  return app.decorator = function(decorator) {
    return decor.use(decorator);
  };
};
