// Generated by CoffeeScript 1.6.3
var DecorFactory, DecorableView, ViewStates, dref, generateId, type, _,
  __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

_ = require("underscore");

generateId = require("../../utils/idGenerator");

dref = require("dref");

ViewStates = require("./states");

type = require("type-component");

DecorFactory = require("./decor/factory");

DecorableView = (function(_super) {
  __extends(DecorableView, _super);

  /*
  */


  function DecorableView(data) {
    var _ref, _ref1, _ref2, _ref3;
    if (data == null) {
      data = {};
    }
    this._onRemoved = __bind(this._onRemoved, this);
    this._onRemove = __bind(this._onRemove, this);
    this._onRendered = __bind(this._onRendered, this);
    this._onRender = __bind(this._onRender, this);
    this.dispose = __bind(this.dispose, this);
    this._init = __bind(this._init, this);
    this.remove = __bind(this.remove, this);
    this.render = __bind(this.render, this);
    this._id = (_ref = (_ref1 = (_ref2 = data.model) != null ? typeof _ref2.get === "function" ? _ref2.get("_id") : void 0 : void 0) != null ? _ref1 : (_ref3 = data.model) != null ? _ref3._id : void 0) != null ? _ref : generateId();
    data["this"] = this;
    DecorableView.__super__.constructor.call(this, data);
  }

  /*
   returns path to this view. Useful for debugging.
  */


  DecorableView.prototype.path = function() {
    var cp, path;
    path = [];
    cp = this;
    while (cp) {
      path.unshift(cp.constructor.name);
      cp = cp._parent;
    }
    return path.join(".");
  };

  /*
  */


  DecorableView.prototype.render = function(next) {
    var _this = this;
    this._init();
    this._onRender();
    this.emit("render");
    return this.callstack.push(function() {
      if (typeof next === "function") {
        next();
      }
      _this._onRendered();
      return _this.emit("rendered");
    });
  };

  /*
  */


  DecorableView.prototype.remove = function(next) {
    var _this = this;
    this.emit("remove");
    this._onRemove();
    return this.callstack.push(function() {
      if (typeof next === "function") {
        next();
      }
      return _this._onRemoved();
    });
  };

  /*
   returns a search for a particular element
   TODO - this shouldn't really exist - leave it up
   to any decorator to implement this, or place it in 
   a utility function
  */


  DecorableView.prototype.$ = function(search) {
    var el;
    el = $(this.section.getChildNodes());
    if (arguments.length) {
      return el.find(search);
    }
    return el;
  };

  /*
   attaches to an element to the DOM
  */


  DecorableView.prototype.attach = function(element, next) {
    var _this = this;
    return this.render(function() {
      (element[0] || element).appendChild(_this.section.toFragment());
      return typeof next === "function" ? next() : void 0;
    });
  };

  /*
   dynamically added decorators
  */


  DecorableView.prototype.decorate = function(options) {
    return DecorFactory.setup(this, options);
  };

  /*
  */


  DecorableView.prototype._init = function(event) {
    if (this._initialized) {
      return;
    }
    this._initialized = true;
    return DecorFactory.setup(this);
  };

  /*
  */


  DecorableView.prototype.dispose = function() {
    var _ref;
    DecorableView.__super__.dispose.call(this);
    if (((_ref = this._parent) != null ? _ref.get("currentState") : void 0) === ViewStates.REMOVING) {
      return;
    }
    return this.section.dispose();
  };

  /*
  */


  DecorableView.prototype._initDecor = function() {
    return DecorFactory.setup(this);
  };

  /*
  */


  DecorableView.prototype._onRender = function() {};

  DecorableView.prototype._onRendered = function() {};

  /*
  */


  DecorableView.prototype._onRemove = function() {};

  DecorableView.prototype._onRemoved = function() {
    return this.dispose();
  };

  /*
   expose this so third-party modules can add a decorator
  */


  DecorableView.addDecoratorClass = DecorFactory.addDecoratorClass;

  return DecorableView;

})(require("./index"));

module.exports = DecorableView;
