// Generated by CoffeeScript 1.6.3
var DecorFactory, DecorableView, ViewCollection, ViewStates, dref, generateId, type, _,
  __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

_ = require("underscore");

ViewCollection = require("./collection");

generateId = require("../../utils/idGenerator");

dref = require("dref");

ViewStates = require("./states");

type = require("type-component");

DecorFactory = require("./decor/factory");

DecorableView = (function(_super) {
  __extends(DecorableView, _super);

  /*
  */


  function DecorableView(data) {
    var _ref, _ref1, _ref2, _ref3;
    if (data == null) {
      data = {};
    }
    this._onRemoved = __bind(this._onRemoved, this);
    this._onRemove = __bind(this._onRemove, this);
    this._onDisplayed = __bind(this._onDisplayed, this);
    this._onDisplay = __bind(this._onDisplay, this);
    this._onRendered = __bind(this._onRendered, this);
    this._onRender = __bind(this._onRender, this);
    this._onLoaded = __bind(this._onLoaded, this);
    this._onLoad = __bind(this._onLoad, this);
    this.dispose = __bind(this.dispose, this);
    this._init = __bind(this._init, this);
    this._id = (_ref = (_ref1 = (_ref2 = data.model) != null ? typeof _ref2.get === "function" ? _ref2.get("_id") : void 0 : void 0) != null ? _ref1 : (_ref3 = data.model) != null ? _ref3._id : void 0) != null ? _ref : generateId();
    data.currentState = ViewStates.NONE;
    data["this"] = this;
    DecorableView.__super__.constructor.call(this, data);
  }

  /*
  */


  DecorableView.prototype.init = function() {
    DecorableView.__super__.init.call(this);
    this.decorators = this.loadables = new ViewCollection();
    this.decorators.view = this;
    return this._initListeners();
  };

  /*
   returns path to this view
  */


  DecorableView.prototype.path = function() {
    var cp, path;
    path = [];
    cp = this;
    while (cp) {
      path.unshift(cp.constructor.name);
      cp = cp._parent;
    }
    return path.join(".");
  };

  /*
  */


  DecorableView.prototype.load = function(next) {
    return this.decorators.load(next);
  };

  DecorableView.prototype.render = function(next) {
    return this.decorators.render(next);
  };

  DecorableView.prototype.display = function(next) {
    return this.decorators.display(next);
  };

  DecorableView.prototype.remove = function(next) {
    return this.decorators.remove(next);
  };

  /*
   returns a search for a particular element
   TODO - this shouldn't really exist - leave it up
   to any decorator to implement this, or place it in 
   a utility function
  */


  DecorableView.prototype.$ = function(search) {
    var el;
    el = $(this.section.getChildNodes());
    if (arguments.length) {
      return el.find(search);
    }
    return el;
  };

  /*
   attaches to an element to the DOM
  */


  DecorableView.prototype.attach = function(element, callback) {
    var _this = this;
    this._domElement = element[0] || element;
    this.decorators.once("display", function() {
      return _this._domElement.appendChild(_this.section.toFragment());
    });
    return this.display(callback);
  };

  /*
   dynamically added decorators
  */


  DecorableView.prototype.decorate = function(options) {
    return DecorFactory.setup(this, options);
  };

  /*
  */


  DecorableView.prototype._init = function(event) {
    if (this._initialized) {
      return;
    }
    this._initialized = true;
    this._initDecor();
    return this._initBindings();
  };

  /*
  */


  DecorableView.prototype.dispose = function() {
    var _ref;
    DecorableView.__super__.dispose.call(this);
    if (((_ref = this._parent) != null ? _ref.get("currentState") : void 0) === ViewStates.REMOVING) {
      return;
    }
    return this.section.dispose();
  };

  /*
  */


  DecorableView.prototype._initListeners = function() {
    this.decorators.on({
      load: this._onLoad,
      loaded: this._onLoaded,
      render: this._onRender,
      rendered: this._onRendered,
      display: this._onDisplay,
      displayed: this._onDisplayed,
      remove: this._onRemove,
      removed: this._onRemoved
    });
    return this.decorators.once("stateChange", this._init);
  };

  /*
  */


  DecorableView.prototype._initDecor = function() {
    return DecorFactory.setup(this);
  };

  /*
  */


  DecorableView.prototype._initBindings = function() {
    return this.decorators.bind("currentState").to(this, "currentState").now();
  };

  /*
  */


  DecorableView.prototype._onLoad = function() {};

  DecorableView.prototype._onLoaded = function() {};

  /*
  */


  DecorableView.prototype._onRender = function() {};

  DecorableView.prototype._onRendered = function() {};

  /*
  */


  DecorableView.prototype._onDisplay = function() {};

  DecorableView.prototype._onDisplayed = function() {};

  /*
  */


  DecorableView.prototype._onRemove = function() {};

  DecorableView.prototype._onRemoved = function() {
    return this.dispose();
  };

  /*
   expose this so third-party modules can add a decorator
  */


  DecorableView.addDecoratorClass = DecorFactory.addDecoratorClass;

  return DecorableView;

})(require("./index"));

module.exports = DecorableView;
