// Generated by CoffeeScript 1.6.3
var BaseView, BindableInheritableObject, flatstack, loaf, models,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

BindableInheritableObject = require("../../bindable/inheritable");

models = require("../../models");

loaf = require("loaf");

flatstack = require("flatstack");

BaseView = (function(_super) {
  __extends(BaseView, _super);

  /*
  */


  BaseView.prototype.__isView = true;

  /*
  */


  BaseView.prototype.models = models;

  /*
  */


  function BaseView(data) {
    if (data == null) {
      data = {};
    }
    BaseView.__super__.constructor.call(this, data);
    this.set("models", models);
    this.section = loaf();
    this.callstack = flatstack();
    this.init();
  }

  /*
  */


  BaseView.prototype.init = function() {};

  BaseView.prototype.render = function(next) {
    return typeof next === "function" ? next() : void 0;
  };

  BaseView.prototype.remove = function(next) {
    return typeof next === "function" ? next() : void 0;
  };

  return BaseView;

})(BindableInheritableObject);

module.exports = BaseView;
