


define(["require", "modules/mojo/interm/mediator/mediator", "hooks"], function(require) {

    var __dirname = "modules/mojo/interm/mediator",
    __filename    = "modules/mojo/interm/mediator/index.js",
    module        = { exports: {} },
    exports       = module.exports,
    define        = undefined,
    window        = exports,
    global        = window;

    

    // Generated by CoffeeScript 1.6.2
(function() {
  var Mediator, hooks;

  Mediator = require("modules/mojo/interm/mediator/mediator");

  hooks = require("hooks");

  module.exports = new Mediator();

}).call(this);


    return module.exports;
});